// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EllipsisBlock: typeof import('./src/components/EllipsisBlock.vue')['default']
    EllipsisPopover: typeof import('./src/components/EllipsisPopover.vue')['default']
  }
}
